### PR TITLE
Improve Shopify liquid compatibility

### PR DESCRIPTION
**Pull request by tuanpham-dev**
- Add missing keywords.
- Add json syntax for schema tag.
- Add javascript syntax for javascript tag.
- Add css syntax for style and stylesheet tags.

### CODE REVIEW

**Comment by tpope** [comment]
Where is this documented? When I Google "liquid shopify javascript" I don't see anything that looks like `{% javascript %}`.

**Comment by tuanpham-dev** [comment]
@tpope - Try this https://shopify.dev/themes/architecture/sections/section-assets#javascript

**Comment by tpope** [comment]
Can we tease apart the Shopify specific stuff and the generic stuff (e.g., `render`) so I can assess them separately?

**Comment by tuanpham-dev** [comment]
@tpope - Please check it again.

**Comment by tpope** [comment]
Your change is informative, but what I was actually asking for was a separate PR for the non-Shopify changes. Those changes are very easy to assess and merge, so I'd like to get them out of the way first.

**Comment by tuanpham-dev** [comment]
I have removed Shopify stuff, could you let me know if it looks good? I will add new PR for Shopify stuff.

**Pull request merged**
